### ISSUE TITLE
Error creating a dataset 

### ISSUE THREAD

**Issue by MubashirullahD** [sl-community/install-sql-ledger#4]
Error message: ;
Just a semi-colon.

I start by creating a dataset:
![sql-ledger](https://user-images.githubusercontent.com/45071858/150974241-aaa60363-2a82-4f78-b507-ebec344d9a09.png)

When I enter this page, I firstly dont see the option to enter company name. Clicking continue takes me to the error page.

![sql-ledger-dataset-creation](https://user-images.githubusercontent.com/45071858/150974549-add7cb8c-9b0d-4bbd-a532-b0d5d370492d.png)

Error:
![sql-ledger-dataset-creation-failure](https://user-images.githubusercontent.com/45071858/150974791-73d83a2f-3c73-4398-b341-ea4951ff0b14.png)

I have not created any users and none existed by default.

I've only changed the password to sql-ledger and removed the german language in the setup.yml (which did not work.)

**Comment by sweitmann** [comment]
Hi Mubashir,

This is probably due to the LC_CTYPE/LC_COLLATE setting, which I assume is missing on your server. 

If you comment out rows 1471 and 1472 in sql-ledger/bin/mozilla/admin.pl with  at the end it should work for you. 

![Bildschirmfoto 2022-01-25 um 16 36 00](https://user-images.githubusercontent.com/100664/151008020-422ead28-2530-4e5d-91ac-f090ddf85703.png)


Please try and advise!

Regards

**Comment by MubashirullahD** [comment]
I forked the repo, made the change in mine, updated the variable to the new repo and it seems to have worked.

![image](https://user-images.githubusercontent.com/45071858/151113625-38fb9cfc-f51b-48d9-80ef-4c026fd8e6cc.png)

Any guidance on the language issue? I removed the german part in the setup and it still didn't change anything. Thanks

**Comment by sweitmann** [comment]
Hi Mubashir, 

Well done. The language for login and admin is set in sql-ledger/sql-ledger.conf:

![Bildschirmfoto 2022-01-26 um 14 15 02](https://user-images.githubusercontent.com/100664/151169570-1612dd2f-e515-4791-8438-d740c9bf50d9.png)

Regards

**Comment by sweitmann** [comment]
Hi Mubashir,

I hope you are doing fine. 

Were you able to solve your issue accordingly?

Regards

**Comment by MubashirullahD** [comment]
Yes, Sebastian. Thanks to you, it has been solved.
